export type QuoteTag = 'mamba' | 'work' | 'resilience' | 'focus' | 'learning' | 'health';

export interface Quote {
  id: string;
  text: string;
  textJa: string;
  author: string;
  authorJa: string;
  tags: QuoteTag[];
  story: string;
}

export const quotes: Quote[] = [
  {
    id: 'kobe-01',
    text: 'Everything negative—pressure, challenges—is all an opportunity for me to rise.',
    textJa: 'ネガティブなこと、プレッシャーも挑戦も、すべては自分が成長するチャンスだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'コービーは、重圧を避けるのではなく成長の材料として受け止めました。2008年のインタビューでも、難しい場面ほど自分を高める機会だという姿勢を繰り返し語っています。',
  },
  {
    id: 'kobe-02',
    text: 'The most important thing is to try and inspire people so that they can be great in whatever they want to do.',
    textJa: 'いちばん大切なのは、人が自分の望むことですばらしくなれるよう、励ますことだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: '引退後のコービーは、選手だけでなく若い人を育てることにも力を注ぎました。彼は自分の成功を、他人が自分の道で力を発揮するための刺激にしたいと話していました。',
  },
  {
    id: 'kobe-03',
    text: "If you're afraid to fail, then you're probably going to fail.",
    textJa: '失敗を恐れているなら、おそらく失敗する。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'コービーは、失敗を避ける心が思い切ったプレーを止めると考えていました。彼のキャリアには外したシュートも多くありましたが、最後の一投を任され続けた背景にはこの覚悟があります。',
  },
  {
    id: 'kobe-04',
    text: 'The moment you give up, is the moment you let someone else win.',
    textJa: 'あきらめた瞬間に、誰かに勝利を渡すことになる。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'この言葉は、相手より先に自分が心を折らないという競技者の考えを端的に表します。故障や敗戦を経験しても、試合の最後まで競争を続けたコービーの姿勢と結びついています。',
  },
  {
    id: 'kobe-05',
    text: 'Rest at the end, not in the middle.',
    textJa: '休むのは途中ではなく、最後にしよう。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work', 'focus'],
    story: '2013年4月、アキレス腱を断裂したコービーは倒れた直後に自分で歩いてフリースローラインへ向かい、2本を決めました。ここでいう休息は体を壊すことではなく、最後まで役割を果たす執念を指しています。',
  },
  {
    id: 'kobe-06',
    text: "Job's not finished.",
    textJa: '仕事はまだ終わっていない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: '2009年NBAファイナルでレイカーズが2勝0敗と先行した後、記者に笑顔が少ない理由を聞かれたコービーはこう答えました。優勝を決めるまで途中経過を祝わないという、彼の集中を象徴する一言です。',
  },
  {
    id: 'kobe-07',
    text: 'Those times when you get up early and you work hard, those times you stay up late and you work hard, those times when you do not feel like working—you are actually being disciplined.',
    textJa: '早起きして努力する時、夜遅くまで努力する時、やる気が出ないのに努力する時こそ、規律を身につけている。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: '2016年の引退スピーチで、コービーは気分ではなく習慣が自分を動かした時間を振り返りました。早朝の4時台に始める練習の逸話も、才能より先に規律を置く彼の生活を伝えています。',
  },
  {
    id: 'kobe-08',
    text: 'The biggest mistake is not to shoot at all.',
    textJa: '最大の失敗は、シュートを打たないことだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーは、外すことよりも打つ権利を自分で放棄することを嫌いました。2006年のラプターズ戦で81得点を記録した試合も、攻め続ける判断が結果を生んだ代表例です。',
  },
  {
    id: 'kobe-09',
    text: 'May you always remember to enjoy the road, especially when it’s a hard one.',
    textJa: '特に険しい道を歩く時こそ、その道のりを楽しむことを忘れないでほしい。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'コービーは引退後、競技の結果だけでなく過程そのものに意味があると語りました。長い練習や故障からの回復を振り返り、苦しい時間にも愛着を持てたことが自分を支えたと説明しています。',
  },
  {
    id: 'kobe-10',
    text: "We can always kind of be average and just do what's normal. I'm not in this to do what's normal.",
    textJa: '平均的で普通のことをする道もある。でも、自分は普通を目指しているわけではない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: 'コービーは、周囲と同じ基準に自分を合わせることを目標にしませんでした。高校時代からNBAまで、毎日の準備量を増やすことで普通ではない成果を狙う姿勢を貫いています。',
  },
  {
    id: 'kobe-11',
    text: "I'll do whatever it takes to win games, whether it's sitting on a bench waving a towel, handing a cup of water to a teammate, or hitting the game-winning shot.",
    textJa: '勝つためなら何でもする。ベンチでタオルを振ることも、水を渡すことも、決勝点を決めることも同じだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: 'コービーは勝利への貢献を、得点やスター性だけで測りませんでした。チームのために役割を受け入れるという考えは、若手時代にベンチから学び、後に仲間へ求めた姿勢でもあります。',
  },
  {
    id: 'kobe-12',
    text: 'If you do not believe in yourself no one will do it for you.',
    textJa: '自分を信じなければ、誰も代わりに信じてはくれない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: '高校卒業後にNBAへ進む決断をした時、コービーには経験不足を疑う声がありました。自分の可能性を先に信じて準備を続けたことが、早い段階で先発の座を得る土台になりました。',
  },
  {
    id: 'kobe-13',
    text: 'Dedication makes dreams come true.',
    textJa: '献身的な努力が夢を現実にする。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: 'コービーは夢を願望のままにせず、練習の予定へ変換しました。少年時代に父のプレーを見て欧州で暮らした経験も、バスケットボールへ時間を捧げる決意を強めています。',
  },
  {
    id: 'kobe-14',
    text: 'The beauty in being blessed with talent is rising above doubters to create a beautiful moment.',
    textJa: '才能を与えられた美しさは、疑う人たちを乗り越えて、すばらしい瞬間をつくることにある。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'コービーは才能を、評価されるための飾りではなく責任だと捉えました。批判が強かった時期にも練習量を落とさず、2009年と2010年の連覇で疑念を結果に変えています。',
  },
  {
    id: 'kobe-15',
    text: "I can't relate to lazy people. We don't speak the same language.",
    textJa: '怠ける人の気持ちはわからない。僕たちは同じ言葉を話していない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: 'この強い表現は、コービーが練習への姿勢を妥協しなかったことから生まれました。チームメートにも準備の基準を示しましたが、目的は仲間を責めることではなく勝てる習慣を共有することでした。',
  },
  {
    id: 'kobe-16',
    text: 'The only thing you can control is your effort.',
    textJa: '自分がコントロールできるのは、努力だけだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーは審判の判定や相手のシュートを支配できない一方、自分の準備は選べると考えました。2010年のファイナル第7戦のような苦しい試合でも、守備と走力へ意識を戻しています。',
  },
  {
    id: 'kobe-17',
    text: 'I don’t want to be the next Michael Jordan, I only want to be Kobe Bryant.',
    textJa: '次のマイケル・ジョーダンになりたいのではない。自分はコービー・ブライアントになりたい。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'ジョーダンを尊敬しながらも、コービーは模倣で終わることを拒みました。似たプレースタイルを指摘された時も、自分の経験と判断で独自の選手像をつくることを選びました。',
  },
  {
    id: 'kobe-18',
    text: 'The topic of failure doesn’t exist.',
    textJa: '失敗という話題は存在しない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'コービーは失敗を終点ではなく、次の修正点として扱いました。若い頃にプレーオフで苦戦した経験も、映像を見直して技術と判断を組み立て直す材料になっています。',
  },
  {
    id: 'kobe-19',
    text: 'Great things come from hard work and perseverance. No excuses.',
    textJa: 'すばらしいものは、努力と粘り強さから生まれる。言い訳はしない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: 'コービーは練習できない理由を並べるより、できる準備を探す人でした。指の故障や膝の痛みを抱えながらも、方法を変えて競技を続けた経歴がこの言葉を裏づけています。',
  },
  {
    id: 'kobe-20',
    text: 'The most important thing is that your teammates have to know you’re pulling for them and you really want them to be successful.',
    textJa: '最も大切なのは、仲間が、自分が応援していて成功を願っていると知ることだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: 'コービーは厳しい要求をする一方、仲間の成功を本気で望むことをリーダーの条件にしました。パウ・ガソルらとの関係でも、勝利だけでなく互いの成長を支える姿勢を重視しています。',
  },
  {
    id: 'kobe-21',
    text: 'Haters are a good problem to have. Nobody hates the good ones. They hate the great ones.',
    textJa: '嫌われることは、よい悩みだ。誰もよい選手を嫌わない。偉大な選手を嫌うのだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'コービーは批判の量を、注目される仕事の副作用として受け止めました。2000年代にリーグ有数の得点者として敵地の反発を浴びても、評価争いより試合の準備へ戻る姿勢を崩しませんでした。',
  },
  {
    id: 'kobe-22',
    text: 'Love me or hate me, they both get me energized.',
    textJa: '愛されても嫌われても、どちらも自分の力になる。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーは観客やメディアの反応を、感情の中心に置くのではなく燃料に変えました。敵地でのブーイングにもホームの期待にも同じ準備で向き合い、外部の声から主導権を取り戻しています。',
  },
  {
    id: 'kobe-23',
    text: 'I don’t have to prove anything to anybody.',
    textJa: '誰かに証明しなければならないことはない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーは記録を追いながらも、他人の承認だけを目的にしませんでした。引退時には、20年間で得たものを順位や比較ではなく、愛した競技への仕事として振り返っています。',
  },
  {
    id: 'kobe-24',
    text: 'Winning takes priority over all else. There is no gray area.',
    textJa: '勝つことが何より優先だ。曖昧な領域はない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーにとって勝利は、個人記録よりチームの目的を優先する基準でした。シュート本数を抑える試合や守備に徹する試合も、勝つために必要なら受け入れています。',
  },
  {
    id: 'kobe-25',
    text: 'Once you know what failure feels like, determination chases success.',
    textJa: '失敗がどんなものか知れば、決意が成功を追いかける。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: '若いコービーはプレーオフで重要なシュートを何度も外し、その映像と向き合いました。失敗の感触を知った後に練習の焦点が明確になり、後年の終盤の強さへつながっています。',
  },
  {
    id: 'kobe-26',
    text: 'A lot of people say they want to be great, but they’re not willing to make the sacrifices necessary to achieve greatness.',
    textJa: '偉大になりたいと言う人は多いが、そのために必要な犠牲を払おうとはしない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: 'コービーは、偉大さを望む言葉と日々の選択を分けて考えました。早朝練習、食事管理、休暇中の自主練習まで、目標には時間と快適さを手放す代価があると示しています。',
  },
  {
    id: 'kobe-27',
    text: 'I focus on one thing and one thing only: that’s trying to win as many championships as I can.',
    textJa: 'ひとつだけに集中する。できる限り多くの優勝を目指すことだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーは個人の得点王より、チームとして優勝することを最終的な軸に置きました。5度のNBA優勝を経験しても、次のシーズンには再び同じ目的へ練習を組み直しています。',
  },
  {
    id: 'kobe-28',
    text: 'The last time I was intimidated was when I was 6 years old in a karate class.',
    textJa: '最後に怖気づいたのは、6歳で空手のクラスにいた時だ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'この発言は、恐怖が消えるという意味ではなく、恐怖を行動の決定者にしないというコービーの冗談まじりの説明です。試合前の緊張を認めつつ、コートでは準備した動作に集中しました。',
  },
  {
    id: 'kobe-29',
    text: 'I have self-doubt. I have insecurity. I have fear of failure. I have nights when I show up at the arena and I’m like, “My back hurts, my feet hurt, my knees hurt.”',
    textJa: '自分を疑うことも、不安も、失敗への恐れもある。それでもアリーナに立つ夜がある。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'resilience'],
    story: 'コービーは不安や痛みを持たない超人として自分を描きませんでした。2015年のインタビューで弱さを率直に語りながら、感情がある状態でも準備と役割を果たせると伝えています。',
  },
  {
    id: 'kobe-30',
    text: 'Heroes come and go, but legends are forever.',
    textJa: '英雄は現れては去るが、伝説は永遠に残る。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'work'],
    story: 'コービーは一時的な人気ではなく、長く人を動かす仕事を意識していました。現役中から物語づくりや映像制作にも取り組み、引退後は短編映画でアカデミー賞を受けています。',
  },
  {
    id: 'kobe-31',
    text: 'I’m reflective only in the sense that I learn to move forward.',
    textJa: '振り返るのは、前へ進むために学ぶという意味でだけだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'learning'],
    story: 'コービーは過去を懐かしむためではなく、次の改善点を見つけるために映像を見返しました。勝った試合にも失敗した試合にも同じように学びを探すのが、彼の分析習慣でした。',
  },
  {
    id: 'kobe-32',
    text: 'The important thing is to learn from the past, use it as a guide, and move forward.',
    textJa: '大切なのは過去から学び、それを道しるべにして前進することだ。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'learning'],
    story: 'コービーは敗戦を人格への判決にせず、戦術と習慣を直す資料として扱いました。ファイナルでの敗北後にプレーの選択や体づくりを変え、次のシーズンへ具体的な修正を持ち込みました。',
  },
  {
    id: 'kobe-33',
    text: 'If you are going to be a leader, you are not going to satisfy everybody.',
    textJa: 'リーダーになるなら、全員を満足させることはできない。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーはリーダーが好かれることと、必要なことを言うことは別だと考えました。若手へ厳しい練習を求めた時も、短期的な反発よりチームの基準を優先しています。',
  },
  {
    id: 'kobe-34',
    text: 'I’m chasing perfection.',
    textJa: '自分は完璧を追いかけている。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーのいう完璧は、ミスが一つもない状態ではなく、準備を極限まで高める方向を指しました。2010年のファイナル後にも、勝利の喜びと同時に次の改善点を探していました。',
  },
  {
    id: 'kobe-35',
    text: 'I create my own path. It was straight and narrow and I looked at it as in between me and everybody else.',
    textJa: '自分の道をつくる。その道はまっすぐで狭く、そこには自分と他のすべての人との距離があった。',
    author: 'Kobe Bryant',
    authorJa: 'コービー・ブライアント',
    tags: ['mamba', 'focus'],
    story: 'コービーはジョーダンとの比較を受けながらも、同じ答えを再現することを目指しませんでした。欧州育ちの経験や独自の練習法を含め、自分の道を狭く深く掘ることで選手像を築きました。',
  },

  {
    id: 'jordan-01',
    text: 'Some people want it to happen, some wish it would happen, others make it happen.',
    textJa: '起きてほしいと願う人もいる。起きればいいと思う人もいる。起こす人もいる。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['work', 'focus'],
    story: 'ジョーダンは成功を願望ではなく行動の問題として語りました。1991年の初優勝まで何度もプレーオフで敗れた経験があり、練習で結果を引き寄せる考えがこの言葉に表れています。',
  },
  {
    id: 'jordan-02',
    text: 'I’ve failed over and over and over again in my life. And that is why I succeed.',
    textJa: '人生で何度も何度も失敗した。だからこそ成功した。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['resilience', 'work'],
    story: 'この言葉はナイキの「Failure」広告で広く知られています。高校2年生の時に代表チームから外れた経験を含め、失敗を練習の理由へ変えた物語として語られました。',
  },
  {
    id: 'jordan-03',
    text: 'Talent wins games, but teamwork and intelligence wins championships.',
    textJa: '才能は試合に勝たせるが、チームワークと知性が優勝をもたらす。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['work', 'learning'],
    story: 'ジョーダンは個人能力だけでは6度の優勝を説明できないと知っていました。スコッティ・ピッペンやフィル・ジャクソンとの連携を深め、個人の得点力をチームの仕組みに組み込んでいます。',
  },
  {
    id: 'jordan-04',
    text: 'I can accept failure, everyone fails at something. But I can’t accept not trying.',
    textJa: '失敗は受け入れられる。誰もが何かで失敗する。でも、挑戦しないことは受け入れられない。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['resilience', 'focus'],
    story: 'ジョーダンは、結果が悪い日にも挑戦した事実を残すことを大切にしました。勝負どころでボールを要求し続けた姿勢は、成功率より挑戦の責任を重視する考えから生まれています。',
  },
  {
    id: 'jordan-05',
    text: 'If you accept the expectations of others, especially negative ones, then you never will change the outcome.',
    textJa: '他人の期待、特に否定的な期待を受け入れたら、結果を変えられない。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['resilience', 'focus'],
    story: '高校時代に代表から外されたジョーダンは、その評価を最終判定にしませんでした。夏の練習で体格と技術を伸ばし、翌年に自分の位置を変えた経験が言葉の背景にあります。',
  },
  {
    id: 'jordan-06',
    text: 'You must expect great things of yourself before you can do them.',
    textJa: 'すばらしいことを成し遂げる前に、まず自分にそれを期待しなければならない。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['focus', 'work'],
    story: 'ジョーダンは試合前から自分が重要な役割を担うと想定して準備しました。期待は自信の演出ではなく、必要な練習量と判断を先に決めるための基準でした。',
  },
  {
    id: 'jordan-07',
    text: 'To learn to succeed, you must first learn to fail.',
    textJa: '成功を学ぶには、まず失敗を学ばなければならない。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['learning', 'resilience'],
    story: 'ジョーダンの初期キャリアには、プレーオフでピストンズに敗れ続けた時期がありました。そこで体を強くし、接触への対応を改良した経験が、後の優勝へつながりました。',
  },
  {
    id: 'jordan-08',
    text: 'I’ve always believed that if you put in the work, the results will come.',
    textJa: '努力をすれば、結果はついてくるといつも信じていた。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['work', 'focus'],
    story: 'ジョーダンは試合の華やかさより、練習で同じ動作を反復する時間を信頼しました。ブルズの練習で競争を激しくしたことも、結果を偶然に任せないための方法でした。',
  },
  {
    id: 'jordan-09',
    text: 'Limits, like fears, are often just an illusion.',
    textJa: '限界は、恐怖と同じで、しばしばただの幻想だ。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['resilience', 'focus'],
    story: 'ジョーダンは、できないという先入観を試合前に固定しませんでした。38度以上の発熱でプレーした「Flu Game」のように、現実の制約を認めながらも役割を探す姿勢を見せています。',
  },
  {
    id: 'jordan-10',
    text: 'There is no such thing as a perfect basketball player, and I don’t believe there is one greatest player either.',
    textJa: '完璧なバスケットボール選手はいないし、唯一最高の選手がいるとも思わない。',
    author: 'Michael Jordan',
    authorJa: 'マイケル・ジョーダン',
    tags: ['learning', 'resilience'],
    story: '殿堂入りスピーチでも、ジョーダンは自分を完成した存在として語りませんでした。競争相手やチームメートに感謝を示し、成長は他者との関係の中で続くものだと振り返っています。',
  },

  {
    id: 'ali-01',
    text: 'He who is not courageous enough to take risks will accomplish nothing in life.',
    textJa: 'リスクを取る勇気がない人は、人生で何も成し遂げられない。',
    author: 'Muhammad Ali',
    authorJa: 'モハメド・アリ',
    tags: ['resilience', 'focus'],
    story: 'アリは徴兵拒否による資格停止という大きな代償を知りながら、自分の信念を曲げませんでした。復帰後も、競技の勝敗だけでなく社会的な立場を引き受ける勇気を示しています。',
  },
  {
    id: 'ali-02',
    text: 'I am the greatest, I said that even before I knew I was.',
    textJa: '私は最高だ。そう言ったのは、そうなる前からだ。',
    author: 'Muhammad Ali',
    authorJa: 'モハメド・アリ',
    tags: ['focus', 'work'],
    story: 'アリは試合前の宣言を、相手を揺さぶる演出であると同時に自分を奮い立たせる言葉として使いました。若い頃から大胆に名乗り、実績を後から積み上げて言葉を現実に近づけました。',
  },
  {
    id: 'ali-03',
    text: 'It isn’t the mountains ahead to climb that wear you out; it’s the pebble in your shoe.',
    textJa: '疲れさせるのは目の前の山ではなく、靴の中の小石だ。',
    author: 'Muhammad Ali',
    authorJa: 'モハメド・アリ',
    tags: ['focus', 'resilience'],
    story: 'アリは大きな目標そのものより、集中を乱す小さな問題に注意を向けました。長いキャンプでは、相手の研究だけでなく睡眠や気持ちの揺れを整えることも勝負の一部でした。',
  },
  {
    id: 'ali-04',
    text: 'The man who views the world at 50 the same as he did at 20 has wasted 30 years of his life.',
    textJa: '50歳で20歳の時と同じ世界の見方をしているなら、30年を無駄にしたことになる。',
    author: 'Muhammad Ali',
    authorJa: 'モハメド・アリ',
    tags: ['learning', 'resilience'],
    story: 'アリはボクサーとしてだけでなく、政治や人種差別について考えを変化させた人物でした。経験を積んでも若い頃の見方に固執せず、学び直すことを成熟の証と捉えています。',
  },
  {
    id: 'ali-05',
    text: 'Float like a butterfly, sting like a bee.',
    textJa: '蝶のように舞い、蜂のように刺す。',
    author: 'Muhammad Ali',
    authorJa: 'モハメド・アリ',
    tags: ['focus', 'work'],
    story: 'この有名なフレーズは、アリの軽いフットワークと鋭いパンチを詩的に表したものです。1964年のソニー・リストン戦で見せた速度と距離感が、言葉を象徴的なものにしました。',
  },
  {
    id: 'ali-06',
    text: 'It’s not bragging if you can back it up.',
    textJa: '実力で裏づけられるなら、それは自慢ではない。',
    author: 'Muhammad Ali',
    authorJa: 'モハメド・アリ',
    tags: ['work', 'focus'],
    story: 'アリの派手な自己宣伝は、リング上の準備と結果によって支えられていました。言葉だけで終わらせず、予告した試合展開を実際の技術で証明しようとしたのが彼の流儀です。',
  },

  {
    id: 'ichiro-01',
    text: '小さなことを積み重ねることが、とんでもないところへ行くただひとつの道だと思っています。',
    textJa: '小さなことを積み重ねることが、とんでもないところへ行くただひとつの道だと思っています。',
    author: 'Ichiro Suzuki',
    authorJa: 'イチロー',
    tags: ['work', 'focus'],
    story: 'イチローは、毎日の準備や打席前の手順を長く変えませんでした。日米通算4,000安打の会見でも、偉業は一度の才能ではなく、積み重ねた小さな努力の集まりだと話しています。',
  },
  {
    id: 'ichiro-02',
    text: '努力せずに何かできるようになる人のことを、天才と呼ぶのだと思います。',
    textJa: '努力せずに何かできるようになる人のことを、天才と呼ぶのだと思います。',
    author: 'Ichiro Suzuki',
    authorJa: 'イチロー',
    tags: ['work', 'learning'],
    story: 'イチローは、外から見える才能の裏にある反復練習を何度も説明しました。少年時代から父と続けた練習を振り返り、結果だけを見て天才と呼ぶことへの違和感を語っています。',
  },
  {
    id: 'ichiro-03',
    text: '夢は近づくと目標に変わる。',
    textJa: '夢は近づくと目標に変わる。',
    author: 'Ichiro Suzuki',
    authorJa: 'イチロー',
    tags: ['focus', 'work'],
    story: 'イチローは、遠い夢を具体的な数字や習慣へ落とし込む考えを持っていました。日本での首位打者やメジャーでの安打記録も、日々の目標へ分解して近づいた成果です。',
  },
  {
    id: 'ichiro-04',
    text: '自分の思ったことをやり続けることに、後悔はありません。',
    textJa: '自分の思ったことをやり続けることに、後悔はありません。',
    author: 'Ichiro Suzuki',
    authorJa: 'イチロー',
    tags: ['focus', 'resilience'],
    story: 'イチローは日本のプロ野球からメジャーへ移る時も、自分の打撃を信じる選択をしました。周囲の予想より本人の準備と意思を優先し、移籍後すぐに首位打者と盗塁王を獲得しています。',
  },
  {
    id: 'ichiro-05',
    text: '第三者の評価は、他人の意見ですから、気にしない。',
    textJa: '第三者の評価は、他人の意見ですから、気にしない。',
    author: 'Ichiro Suzuki',
    authorJa: 'イチロー',
    tags: ['focus', 'resilience'],
    story: 'イチローは、打率や安打数が注目される立場でも、評価を一日の感情にしませんでした。自分が管理できる準備や打席の選択へ意識を戻すことで、長いシーズンを安定して戦いました。',
  },
  {
    id: 'ichiro-06',
    text: '準備というのは、言い訳を排除するためにするものです。',
    textJa: '準備というのは、言い訳を排除するためにするものです。',
    author: 'Ichiro Suzuki',
    authorJa: 'イチロー',
    tags: ['work', 'focus'],
    story: 'イチローは試合前の道具、食事、体の状態を細かく整えました。準備を終えておけば、結果が出なかった時に環境のせいにせず、自分の課題を見つめられるという発想です。',
  },
  {
    id: 'ichiro-07',
    text: '苦しみを背負いながら、毎日小さな一歩を進み続けることが、成功への近道です。',
    textJa: '苦しみを背負いながら、毎日小さな一歩を進み続けることが、成功への近道です。',
    author: 'Ichiro Suzuki',
    authorJa: 'イチロー',
    tags: ['resilience', 'work'],
    story: 'イチローは不調や故障があっても、練習を完全に止めるのではなくできる範囲の課題を続けました。2004年にメジャー最多の262安打を記録した年も、毎日の打席を積み上げています。',
  },
  {
    id: 'ichiro-08',
    text: '壁というのは、できる人にしかやってこない。',
    textJa: '壁というのは、できる人にしかやってこない。',
    author: 'Ichiro Suzuki',
    authorJa: 'イチロー',
    tags: ['resilience', 'learning'],
    story: 'イチローは高い水準へ進んだ後に現れる不調を、能力の否定とは考えませんでした。新しい投手や年齢による変化を壁として受け止め、打撃方法を調整し続けています。',
  },

  {
    id: 'serena-01',
    text: 'A champion is defined not by their wins but by how they can recover when they fall.',
    textJa: 'チャンピオンは勝利ではなく、転んだ時にどう立ち直るかで決まる。',
    author: 'Serena Williams',
    authorJa: 'セリーナ・ウィリアムズ',
    tags: ['resilience', 'work'],
    story: 'セリーナは敗戦や出産後の復帰を、キャリアの終わりではなく再出発として扱いました。2018年以降も決勝へ戻り、立て直す力こそ競技者の強さだと示しています。',
  },
  {
    id: 'serena-02',
    text: 'The success of every woman should be the inspiration to another.',
    textJa: 'すべての女性の成功は、別の誰かの励みになるべきだ。',
    author: 'Serena Williams',
    authorJa: 'セリーナ・ウィリアムズ',
    tags: ['work', 'resilience'],
    story: 'セリーナは自分の実績を、後に続く女性の選択肢を広げる力として語りました。テニス界の男女格差について発言し、若い選手への支援や起業にも取り組んでいます。',
  },
  {
    id: 'serena-03',
    text: 'I always believe I can beat the best and achieve the best. I always see myself in the top position.',
    textJa: 'いつも最高の相手に勝ち、最高の結果を出せると信じている。自分を頂点に思い描いている。',
    author: 'Serena Williams',
    authorJa: 'セリーナ・ウィリアムズ',
    tags: ['focus', 'resilience'],
    story: 'セリーナは、強い相手を前にしても自分を頂点へ置くイメージを手放しませんでした。姉妹で競い合いながら世界一を目指した経験が、恐れより準備と自己信頼を先に置く姿勢を育てています。',
  },
  {
    id: 'serena-04',
    text: 'Luck has nothing to do with it, because I have spent many, many hours, countless hours, on the court working for my one moment in time.',
    textJa: '運ではない。たった一度の瞬間のために、数え切れない時間をコートで積み重ねてきた。',
    author: 'Serena Williams',
    authorJa: 'セリーナ・ウィリアムズ',
    tags: ['work', 'focus'],
    story: 'セリーナは優勝の瞬間を偶然の幸運にしないため、幼い頃から父リチャードと練習を重ねました。2017年全豪オープン優勝後も、結果より準備に時間を使ったことを強調しています。',
  },

  {
    id: 'ohtani-01',
    text: '無理だと思われていることを、やってみたい。',
    textJa: '無理だと思われていることを、やってみたい。',
    author: 'Shohei Ohtani',
    authorJa: '大谷翔平',
    tags: ['work', 'resilience'],
    story: '大谷は高校時代から投手と打者の両立を目標に掲げました。周囲に難しいと言われた二刀流を日本とメジャーで実践し、前例の少ない道を自分の練習で形にしています。',
  },
  {
    id: 'ohtani-02',
    text: '誰もやったことがないことをやるのが、僕のモチベーションです。',
    textJa: '誰もやったことがないことをやるのが、僕のモチベーションです。',
    author: 'Shohei Ohtani',
    authorJa: '大谷翔平',
    tags: ['focus', 'work'],
    story: '大谷は投打の両方で一流を目指すことを、周囲との比較ではなく挑戦そのものとして語りました。2021年のア・リーグMVPは、その構想を長期の準備で実現した節目になりました。',
  },
  {
    id: 'ohtani-03',
    text: '先入観は可能性を狭める。',
    textJa: '先入観は可能性を狭める。',
    author: 'Shohei Ohtani',
    authorJa: '大谷翔平',
    tags: ['focus', 'learning'],
    story: '大谷は、投手は打者として成功しにくいという既存の見方をそのまま受け入れませんでした。二刀流を続けるため、体づくりや登板間隔まで自分に合わせて工夫しています。',
  },

  {
    id: 'hanyu-01',
    text: '努力は嘘をつく。でも無駄にはならない。',
    textJa: '努力は嘘をつく。でも無駄にはならない。',
    author: 'Yuzuru Hanyu',
    authorJa: '羽生結弦',
    tags: ['work', 'resilience'],
    story: '羽生は、練習量がいつも得点に直結するわけではない現実を知っていました。2018年平昌五輪では右足首の負傷明けでも、積み重ねた感覚を演技へつなげて連覇を果たしています。',
  },
  {
    id: 'hanyu-02',
    text: '僕はオリンピックを知っているから、オリンピックを知らない人より強い。',
    textJa: '僕はオリンピックを知っているから、オリンピックを知らない人より強い。',
    author: 'Yuzuru Hanyu',
    authorJa: '羽生結弦',
    tags: ['focus', 'learning'],
    story: '羽生は2014年ソチで金メダルを経験した後、五輪の緊張を知ること自体を強みに変えました。平昌ではその経験を演技構成と心の準備に生かし、同じ舞台で再び頂点に立ちました。',
  },
  {
    id: 'hanyu-03',
    text: '自分の弱さを認められる人は、強い人だと思います。',
    textJa: '自分の弱さを認められる人は、強い人だと思います。',
    author: 'Yuzuru Hanyu',
    authorJa: '羽生結弦',
    tags: ['resilience', 'learning'],
    story: '羽生は演技後の会見で、失敗したジャンプや体の状態を率直に振り返りました。弱点を隠すより練習課題として言葉にすることで、次の演技へ改善を持ち込んでいます。',
  },

  {
    id: 'inoue-01',
    text: '努力は必ず報われるとは限らない。でも、努力しなければ報われることはない。',
    textJa: '努力は必ず報われるとは限らない。でも、努力しなければ報われることはない。',
    author: 'Naoya Inoue',
    authorJa: '井上尚弥',
    tags: ['work', 'resilience'],
    story: '井上は世界戦へ向けた減量や反復練習について、努力が勝利を保証するわけではないと現実的に語ります。それでも勝負の準備をやめれば可能性は消えるという、ボクサーとしての覚悟が込められています。',
  },
  {
    id: 'inoue-02',
    text: '自分に勝つことが一番難しい。',
    textJa: '自分に勝つことが一番難しい。',
    author: 'Naoya Inoue',
    authorJa: '井上尚弥',
    tags: ['focus', 'resilience'],
    story: '井上は相手の研究と同じくらい、自分の慢心を抑えることを重視しています。統一戦を重ねて評価が高まった後も、毎試合の計量と練習を一からやり直す姿勢を続けました。',
  },

  {
    id: 'arnold-01',
    text: 'The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character.',
    textJa: 'ジムで体を使って戦う抵抗も、人生で戦う抵抗も、強い人格をつくる。',
    author: 'Arnold Schwarzenegger',
    authorJa: 'アーノルド・シュワルツェネッガー',
    tags: ['work', 'resilience', 'health'],
    story: 'アーノルドはボディビルの負荷と、移民として米国で道を開いた経験を重ねて語りました。筋肉を鍛える習慣だけでなく、俳優や政治家へ転身する際の困難も人格を形づくったと説明しています。',
  },
  {
    id: 'arnold-02',
    text: 'You must have a goal, a clear goal, a goal that you can visualize.',
    textJa: '目標を持たなければならない。明確で、思い描ける目標を。',
    author: 'Arnold Schwarzenegger',
    authorJa: 'アーノルド・シュワルツェネッガー',
    tags: ['focus', 'work'],
    story: 'アーノルドは若い頃、ボディビルの世界王者とハリウッド進出を具体的な目標にしました。写真や言葉で完成した姿を思い描き、そこから必要な練習と行動を逆算しています。',
  },
  {
    id: 'arnold-03',
    text: 'The worst thing I can be is the same as everybody else. I hate that.',
    textJa: '最悪なのは、他の人と同じになることだ。それが嫌いだ。',
    author: 'Arnold Schwarzenegger',
    authorJa: 'アーノルド・シュワルツェネッガー',
    tags: ['focus', 'work'],
    story: 'アーノルドは、訛りや体格が俳優として不利だと言われても個性を消しませんでした。人と違う体つきと経歴をむしろ武器として磨き、既存の役柄に収まらないキャリアを作りました。',
  },

  {
    id: 'goggins-01',
    text: 'When you think you are done, you are only at 40 percent of your body’s capability.',
    textJa: 'もう限界だと思った時、体の能力はまだ40パーセントしか使っていない。',
    author: 'David Goggins',
    authorJa: 'デイビッド・ゴギンズ',
    tags: ['resilience', 'health'],
    story: 'ゴギンズは著書で、限界感覚は安全装置のように早く現れるという自分の体験を語りました。40パーセントという数字は医学的な測定値ではなく、苦しい時にもう一段進むための比喩です。',
  },
  {
    id: 'goggins-02',
    text: 'The most important conversations you’ll ever have are the ones you’ll have with yourself.',
    textJa: '人生で最も大切な会話は、自分自身との会話だ。',
    author: 'David Goggins',
    authorJa: 'デイビッド・ゴギンズ',
    tags: ['focus', 'resilience'],
    story: 'ゴギンズは幼少期の困難や軍隊での訓練を通じて、内側の言い訳と向き合う方法を身につけました。毎日の自己対話を記録し、気分ではなく決めた行動へ戻る習慣を勧めています。',
  },
  {
    id: 'goggins-03',
    text: 'Suffering is a test. That is all it is.',
    textJa: '苦しみは試験だ。それ以上でも以下でもない。',
    author: 'David Goggins',
    authorJa: 'デイビッド・ゴギンズ',
    tags: ['resilience', 'work'],
    story: 'ゴギンズは極限の持久走や軍の選抜で、苦痛を自分の価値そのものと混同しないようにしました。痛みを観察し、何ができるかを選ぶための試験として捉えるのが彼の実践です。',
  },

  {
    id: 'duckworth-01',
    text: 'Enthusiasm is common. Endurance is rare.',
    textJa: '熱意はよくある。持久力はまれだ。',
    author: 'Angela Duckworth',
    authorJa: 'アンジェラ・ダックワース',
    tags: ['work', 'resilience'],
    story: 'ダックワースは教師と研究者として、最初の熱意だけでは長期の成果を説明できないと観察しました。陸軍士官学校や学生の研究から、興味を持ち続けて努力を更新する力を重視しています。',
  },
  {
    id: 'duckworth-02',
    text: 'Grit is living life like it’s a marathon, not a sprint.',
    textJa: 'やり抜く力とは、人生を短距離走ではなくマラソンとして生きることだ。',
    author: 'Angela Duckworth',
    authorJa: 'アンジェラ・ダックワース',
    tags: ['resilience', 'work'],
    story: '著書『GRIT』で、ダックワースは一時的な努力より長期の関心と粘り強さを研究しました。マラソンの比喩は、速く始めるより目的を保ちながらペースを調整する大切さを示します。',
  },
  {
    id: 'duckworth-03',
    text: 'Our potential is one thing. What we do with it is quite another.',
    textJa: '可能性があることと、それをどう使うかは別のことだ。',
    author: 'Angela Duckworth',
    authorJa: 'アンジェラ・ダックワース',
    tags: ['focus', 'learning'],
    story: 'ダックワースは能力テストの結果だけで将来を決められないと説明しました。持っている力を練習や学習へ変換する過程に、環境と習慣が大きく関わると研究しています。',
  },

  {
    id: 'clear-01',
    text: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    textJa: '目標の高さまで上がるのではない。仕組みの水準まで落ちるのだ。',
    author: 'James Clear',
    authorJa: 'ジェームズ・クリアー',
    tags: ['work', 'focus'],
    story: '『Atomic Habits』でクリアーは、目標だけでは行動を安定させられないと説明しました。読書や運動の時間と場所を先に決めるなど、望む結果を支える仕組みへ焦点を移しています。',
  },
  {
    id: 'clear-02',
    text: 'Every action you take is a vote for the person you wish to become.',
    textJa: 'すべての行動は、なりたい自分への一票だ。',
    author: 'James Clear',
    authorJa: 'ジェームズ・クリアー',
    tags: ['learning', 'focus'],
    story: 'クリアーは、アイデンティティは一度の宣言ではなく反復行動から育つと書きました。一回の読書で専門家にはなれなくても、読書を選ぶたびにその方向へ自分を投票できるという考えです。',
  },
  {
    id: 'clear-03',
    text: 'You should be far more concerned with your current trajectory than with your current results.',
    textJa: '今の結果より、今どちらへ進んでいるかをずっと気にすべきだ。',
    author: 'James Clear',
    authorJa: 'ジェームズ・クリアー',
    tags: ['work', 'resilience'],
    story: 'クリアーは、短期の成果が出ない時でも習慣の方向を点検するよう勧めています。複利のように小さな改善が積み上がるため、今日の数字だけで長期の進路を判断しないという発想です。',
  },

  {
    id: 'bruce-01',
    text: 'Absorb what is useful, discard what is useless and add what is specifically your own.',
    textJa: '役立つものを吸収し、役立たないものを捨て、自分だけのものを加えよ。',
    author: 'Bruce Lee',
    authorJa: 'ブルース・リー',
    tags: ['learning', 'focus'],
    story: 'ブルース・リーは、特定の流派をそのまま守るより実際に役立つ技術を統合しました。截拳道の考え方にも、他人の型を盲目的に真似ず自分の経験で磨く姿勢が表れています。',
  },
  {
    id: 'bruce-02',
    text: 'Knowing is not enough, we must apply. Willing is not enough, we must do.',
    textJa: '知るだけでは足りない。応用しなければならない。意欲だけでは足りない。行動しなければならない。',
    author: 'Bruce Lee',
    authorJa: 'ブルース・リー',
    tags: ['learning', 'work'],
    story: 'リーは武道の知識を、道場で実際に使える動作へ変えることを重視しました。映画の演技でも、考えた技を身体で検証し、見栄えと実用性の両方を追求しています。',
  },
  {
    id: 'bruce-03',
    text: 'A goal is not always meant to be reached, it often serves simply as something to aim at.',
    textJa: '目標は必ずしも到達するためだけのものではない。目指す方向になることも多い。',
    author: 'Bruce Lee',
    authorJa: 'ブルース・リー',
    tags: ['focus', 'learning'],
    story: 'リーは、目標が行動の方向を整える役割にも注目しました。映画や武道で理想の動きを思い描き、完全に届かない日にも練習の焦点を失わないようにしています。',
  },

  {
    id: 'musashi-01',
    text: '千日の稽古を鍛とし、万日の稽古を錬とす。',
    textJa: '千日の稽古を鍛とし、万日の稽古を錬とす。',
    author: 'Miyamoto Musashi',
    authorJa: '宮本武蔵',
    tags: ['work', 'focus'],
    story: '『五輪書』の最後に置かれたこの句は、鍛錬を短期の気合いで終わらせない教えです。千日と万日という長い時間を示し、技を身体に定着させるには継続が必要だと説いています。',
  },
  {
    id: 'musashi-02',
    text: '身を浅く思ひ、世を深く思ふ。',
    textJa: '自分を軽く考え、世の中を深く考える。',
    author: 'Miyamoto Musashi',
    authorJa: '宮本武蔵',
    tags: ['focus', 'learning'],
    story: '武蔵は、自分の都合だけで物事を測らず、相手や全体の流れを見るよう求めました。兵法の教えとして、自己中心の思い込みを減らし状況を広く読む姿勢を表しています。',
  },
  {
    id: 'musashi-03',
    text: '道を広く知り、物毎に少しも迷ひたる事なし。',
    textJa: '道を広く知り、物事に少しも迷うことがない。',
    author: 'Miyamoto Musashi',
    authorJa: '宮本武蔵',
    tags: ['learning', 'focus'],
    story: '『五輪書』で武蔵は、一つの技だけに閉じず兵法全体を学ぶ重要性を述べました。広い視野があれば、場面ごとの判断で迷いにくくなるという実戦的な教えです。',
  },

  {
    id: 'matsushita-01',
    text: '失敗したところでやめてしまうから失敗になる。成功するところまで続ければ、それは成功になる。',
    textJa: '失敗したところでやめてしまうから失敗になる。成功するところまで続ければ、それは成功になる。',
    author: 'Konosuke Matsushita',
    authorJa: '松下幸之助',
    tags: ['resilience', 'work'],
    story: '松下幸之助は、松下電器を小さな会社から大企業へ育てる過程で何度も試行錯誤を重ねました。途中の失敗だけで結論を出さず、改善を続けて結果へ到達する姿勢を社員にも伝えています。',
  },
  {
    id: 'matsushita-02',
    text: '無理に売るな。客の欲しがるものを作れ。',
    textJa: '無理に売るな。客の欲しがるものを作れ。',
    author: 'Konosuke Matsushita',
    authorJa: '松下幸之助',
    tags: ['focus', 'learning'],
    story: '松下は販売員の押し込みより、生活者の不便を理解する商品づくりを重視しました。電池や家電を広く普及させた経営では、売る側の都合より使う人の需要を先に考えています。',
  },
  {
    id: 'matsushita-03',
    text: '素直な心になりましょう。',
    textJa: '素直な心になりましょう。',
    author: 'Konosuke Matsushita',
    authorJa: '松下幸之助',
    tags: ['learning', 'resilience'],
    story: '松下幸之助は著書や講話で、先入観を捨てて事実を受け入れる「素直な心」を経営の基本に置きました。これは松下が好んだ別人の詩の引用ではなく、本人が繰り返した実践的な教えです。',
  },

  {
    id: 'inamori-01',
    text: '人生・仕事の結果＝考え方×熱意×能力',
    textJa: '人生・仕事の結果＝考え方×熱意×能力。',
    author: 'Kazuo Inamori',
    authorJa: '稲盛和夫',
    tags: ['work', 'focus'],
    story: '稲盛和夫は、能力だけで仕事の結果は決まらず、考え方と熱意の向きが掛け算になると説きました。京セラ創業や再建の経験から、利他の考え方が成果の土台になると説明しています。',
  },
  {
    id: 'inamori-02',
    text: 'ど真剣にやる。',
    textJa: 'ど真剣にやる。',
    author: 'Kazuo Inamori',
    authorJa: '稲盛和夫',
    tags: ['work', 'focus'],
    story: '稲盛は「真剣」よりさらに強い言葉で、目の前の仕事へ向き合う姿勢を社員に求めました。京セラの創業期には、資金も設備も乏しい中で一つの技術を磨き続けています。',
  },

  {
    id: 'honda-01',
    text: '成功とは99パーセントの失敗に支えられた1パーセントだ。',
    textJa: '成功とは99パーセントの失敗に支えられた1パーセントだ。',
    author: 'Soichiro Honda',
    authorJa: '本田宗一郎',
    tags: ['resilience', 'work'],
    story: '本田宗一郎は、試作と失敗を繰り返しながら二輪車と自動車の技術を育てました。成功した製品だけを見ず、そこへ至る無数の実験を含めて仕事の成果だと考えています。',
  },
  {
    id: 'honda-02',
    text: '人間、生まれてきたからには、何か一つでいいから世の中のために役立つことをして死にたい。',
    textJa: '人間、生まれてきたからには、何か一つでいいから世の中のために役立つことをして死にたい。',
    author: 'Soichiro Honda',
    authorJa: '本田宗一郎',
    tags: ['work', 'focus'],
    story: '本田宗一郎は、機械を作る目的を会社の規模ではなく人の役に立つことに置きました。自転車用補助エンジンから世界の二輪車メーカーへ進んだ歩みも、実用への執念に支えられています。',
  },

  {
    id: 'jobs-01',
    text: 'The only way to do great work is to love what you do.',
    textJa: 'すばらしい仕事をする唯一の方法は、自分のすることを愛することだ。',
    author: 'Steve Jobs',
    authorJa: 'スティーブ・ジョブズ',
    tags: ['work', 'focus'],
    story: 'ジョブズはスタンフォード大学の卒業式で、仕事は人生の大きな時間を占めるから好きなことを探すべきだと話しました。Appleへ戻った後も、製品の細部へ強い情熱を注いでいます。',
  },
  {
    id: 'jobs-02',
    text: 'Stay hungry, stay foolish.',
    textJa: 'ハングリーであれ。愚かであれ。',
    author: 'Steve Jobs',
    authorJa: 'スティーブ・ジョブズ',
    tags: ['learning', 'focus'],
    story: 'この言葉は2005年のスタンフォード大学卒業式スピーチの結びです。既存の常識に満足せず、未知へ向かう学生たちへ、好奇心と少しの無謀さを持ち続けるよう伝えました。',
  },
  {
    id: 'jobs-03',
    text: 'Your time is limited, so don’t waste it living someone else’s life.',
    textJa: '時間は限られている。だから誰かの人生を生きて無駄にしてはいけない。',
    author: 'Steve Jobs',
    authorJa: 'スティーブ・ジョブズ',
    tags: ['focus', 'resilience'],
    story: 'ジョブズは同じ卒業式で、他人の期待や既成の道に自分の時間を使わないよう語りました。病気を経験した後も、何を作るかを自分の価値観で選ぶ姿勢を貫いています。',
  },

  {
    id: 'rohn-01',
    text: 'Either you run the day or the day runs you.',
    textJa: '一日を動かすのは自分か、それとも一日に動かされるかだ。',
    author: 'Jim Rohn',
    authorJa: 'ジム・ローン',
    tags: ['focus', 'work'],
    story: 'ジム・ローンは、人生を変える大きな決断より毎日の管理を重視した講演家です。朝の計画や学習時間を自分で決めることで、忙しさに流される状態から抜け出すよう勧めました。',
  },
  {
    id: 'rohn-02',
    text: 'Discipline is the bridge between goals and accomplishment.',
    textJa: '規律は、目標と達成をつなぐ橋だ。',
    author: 'Jim Rohn',
    authorJa: 'ジム・ローン',
    tags: ['work', 'focus'],
    story: 'ローンは、目標を紙に書くだけでは生活は変わらないと講演で繰り返しました。毎日同じ小さな行動を選ぶ規律が、遠い成果との間をつなぐという教えです。',
  },

  {
    id: 'seneca-01',
    text: 'We suffer more often in imagination than in reality.',
    textJa: '私たちは現実よりも想像の中で苦しむことが多い。',
    author: 'Seneca',
    authorJa: 'セネカ',
    tags: ['resilience', 'focus'],
    story: 'セネカは『倫理書簡集』で、まだ起きていない災いを心の中で何度も経験する人間の習性を論じました。事実と想像を分けて見ることが、不安を扱う最初の一歩だという教えです。',
  },
  {
    id: 'seneca-02',
    text: 'Difficulties strengthen the mind, as labor does the body.',
    textJa: '労働が体を強くするように、困難は心を強くする。',
    author: 'Seneca',
    authorJa: 'セネカ',
    tags: ['resilience', 'health'],
    story: 'セネカはストア派の哲学者として、困難をただ避けるのではなく判断力を鍛える機会と考えました。肉体の訓練と同じく、心も負荷に向き合うことで強くなると説明しています。',
  },

  {
    id: 'marcus-01',
    text: 'You have power over your mind—not outside events. Realize this, and you will find strength.',
    textJa: 'あなたが支配できるのは心であり、外の出来事ではない。それを理解すれば、強さが見つかる。',
    author: 'Marcus Aurelius',
    authorJa: 'マルクス・アウレリウス',
    tags: ['focus', 'resilience'],
    story: 'ローマ皇帝マルクス・アウレリウスは、戦争や疫病の時代に『自省録』を書きました。外界を完全に動かせなくても、自分の判断と反応は整えられるという実践的な記録です。',
  },
  {
    id: 'marcus-02',
    text: 'The happiness of your life depends upon the quality of your thoughts.',
    textJa: '人生の幸福は、思考の質にかかっている。',
    author: 'Marcus Aurelius',
    authorJa: 'マルクス・アウレリウス',
    tags: ['focus', 'health'],
    story: '『自省録』でマルクスは、出来事そのものより、それをどう判断するかを何度も見直しました。皇帝としての責務の中でも、怒りや欲望を観察し穏やかな行動を選ぼうとしています。',
  },
];
